# spark-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
data:
  spark-defaults.conf: |
    spark.master   spark://localhost:7077
    spark.submit.deployMode cluster
    spark.executor.instances 2
    spark.kubernetes.container.image docker.io/bitnami/spark:3.5
