apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2  # or the desired number of worker replicas
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
      - name: spark-worker
        image: docker.io/bitnami/spark:3.5
        command:
          - "/opt/bitnami/spark/bin/spark-class"
          - "org.apache.spark.deploy.worker.Worker"
          - "spark://spark-master:7077"
        ports:
          - containerPort: 7079

