apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  ports:
    - port: 29092  # Kafka default port
      targetPort: 29092  # Port on which Kafka is running on the external server
  selector:
    app: kafka  # Label selector for the pods running Kafka
